#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

echo "> Clean"

source "$(realpath $(dirname $0))/helper.sh"
dirs=$(filter_existing_dirs $@)

find ./example -type f -name "controller-registration.yaml" -exec rm '{}' \;
find ./example -type f -name "extension.yaml" -exec rm '{}' \;

for source_tree in $dirs; do
  find "$(dirname "$source_tree")" -type f -name "zz_*.go" -exec rm '{}' \;
  grep -lr '// Code generated by MockGen. DO NOT EDIT' "$(dirname "$source_tree")" | xargs rm -f || true
done
